import type {
  EffectivePlanningAssumptions,
  PlanningAssumptionFieldDefinition,
  PlanningAssumptionSectionDefinition,
  PlanningScenarioPreset,
} from "./AssumptionTypes";

export const SYSTEM_DEFAULT_PLANNING_ASSUMPTIONS: EffectivePlanningAssumptions = {
  currentAge: 35,
  retirementAge: 60,
  lifeExpectancy: 90,
  spouseLifeExpectancy: 92,
  salaryGrowthRate: 8,
  bonusGrowthRate: 6,
  businessIncomeGrowth: 7,
  rentalIncomeGrowth: 5,
  otherIncomeGrowth: 4,
  generalInflation: 6,
  medicalInflation: 9,
  educationInflation: 10,
  lifestyleInflation: 7,
  propertyInflation: 5,
  luxuryInflation: 8,
  equityReturn: 12,
  debtReturn: 7,
  goldReturn: 6,
  silverReturn: 5,
  realEstateReturn: 8,
  cashReturn: 4,
  epfReturn: 8.15,
  ppfReturn: 7.1,
  npsEquityReturn: 11,
  npsDebtReturn: 7,
  homeLoanInterest: 8.5,
  carLoanInterest: 9.5,
  personalLoanInterest: 13,
  loanPrepaymentStrategy: "HYBRID",
  incomeTaxRate: 20,
  capitalGainsTax: 10,
  dividendTax: 10,
  rentalTaxRate: 20,
  withdrawalRate: 4,
  retirementExpenseRatio: 85,
  legacyTarget: 0,
  emergencyCorpusMonths: 12,
  goalFundingPriority: "MEDIUM",
};

export const SCENARIO_PRESET_DESCRIPTIONS: Record<PlanningScenarioPreset, string> = {
  BASE: "Balanced planning assumptions aligned to the system baseline.",
  CONSERVATIVE: "Lower return assumptions and higher stress-case inflation inputs.",
  OPTIMISTIC: "Higher growth expectations with milder inflation pressure.",
  CUSTOM: "A fully customizable scenario inheriting from your user defaults.",
};

export const SCENARIO_PRESET_OVERRIDES: Record<PlanningScenarioPreset, Partial<EffectivePlanningAssumptions>> = {
  BASE: {},
  CONSERVATIVE: {
    salaryGrowthRate: 6,
    bonusGrowthRate: 4,
    businessIncomeGrowth: 5,
    rentalIncomeGrowth: 4,
    otherIncomeGrowth: 3,
    generalInflation: 7,
    medicalInflation: 10,
    educationInflation: 11,
    lifestyleInflation: 8,
    propertyInflation: 4,
    luxuryInflation: 9,
    equityReturn: 9,
    debtReturn: 6.5,
    goldReturn: 5.5,
    silverReturn: 4.5,
    realEstateReturn: 6.5,
    cashReturn: 4.5,
    epfReturn: 7.75,
    ppfReturn: 7,
    npsEquityReturn: 9,
    npsDebtReturn: 6.5,
    withdrawalRate: 3.5,
    retirementExpenseRatio: 95,
    emergencyCorpusMonths: 18,
  },
  OPTIMISTIC: {
    salaryGrowthRate: 10,
    bonusGrowthRate: 8,
    businessIncomeGrowth: 10,
    rentalIncomeGrowth: 6,
    otherIncomeGrowth: 5,
    generalInflation: 5,
    medicalInflation: 8,
    educationInflation: 8,
    lifestyleInflation: 6,
    propertyInflation: 6,
    luxuryInflation: 7,
    equityReturn: 14,
    debtReturn: 7.5,
    goldReturn: 7,
    silverReturn: 6.5,
    realEstateReturn: 9,
    epfReturn: 8.4,
    ppfReturn: 7.3,
    npsEquityReturn: 13,
    npsDebtReturn: 7.5,
    withdrawalRate: 5,
    retirementExpenseRatio: 80,
    emergencyCorpusMonths: 9,
  },
  CUSTOM: {},
};

export const PLANNING_ASSUMPTION_SECTIONS: readonly PlanningAssumptionSectionDefinition[] = [
  {
    category: "PERSONAL",
    label: "Personal",
    description: "Longevity and retirement horizon inputs that shape every future plan.",
    fieldKeys: ["currentAge", "retirementAge", "lifeExpectancy", "spouseLifeExpectancy"],
  },
  {
    category: "INCOME",
    label: "Income",
    description: "Growth assumptions for earned, business, rental and supplemental income streams.",
    fieldKeys: ["salaryGrowthRate", "bonusGrowthRate", "businessIncomeGrowth", "rentalIncomeGrowth", "otherIncomeGrowth"],
  },
  {
    category: "INFLATION",
    label: "Inflation",
    description: "Category-specific inflation expectations used across lifestyle and goal planning.",
    fieldKeys: ["generalInflation", "medicalInflation", "educationInflation", "lifestyleInflation", "propertyInflation", "luxuryInflation"],
  },
  {
    category: "INVESTMENTS",
    label: "Investments",
    description: "Long-run expected returns for liquid, retirement and real assets.",
    fieldKeys: ["equityReturn", "debtReturn", "goldReturn", "silverReturn", "realEstateReturn", "cashReturn", "epfReturn", "ppfReturn", "npsEquityReturn", "npsDebtReturn"],
  },
  {
    category: "LOANS",
    label: "Loans",
    description: "Borrowing cost and repayment-policy assumptions for debt-sensitive planning.",
    fieldKeys: ["homeLoanInterest", "carLoanInterest", "personalLoanInterest", "loanPrepaymentStrategy"],
  },
  {
    category: "TAXES",
    label: "Taxes",
    description: "Effective tax assumptions for income, capital gains, dividends and rental cash flow.",
    fieldKeys: ["incomeTaxRate", "capitalGainsTax", "dividendTax", "rentalTaxRate"],
  },
  {
    category: "RETIREMENT",
    label: "Retirement",
    description: "Withdrawal discipline, target spending, legacy planning and emergency corpus assumptions.",
    fieldKeys: ["withdrawalRate", "retirementExpenseRatio", "legacyTarget", "emergencyCorpusMonths"],
  },
] as const;

export const PLANNING_ASSUMPTION_FIELD_DEFINITIONS: readonly PlanningAssumptionFieldDefinition[] = [
  { key: "currentAge", category: "PERSONAL", label: "Current Age", description: "Primary planner age", tooltip: "Used to determine time to retirement and remaining compounding horizon.", inputKind: "integer", min: 18, max: 100, step: 1 },
  { key: "retirementAge", category: "PERSONAL", label: "Retirement Age", description: "Planned retirement age", tooltip: "The assumed age when earned income planning transitions into retirement drawdown.", inputKind: "integer", min: 40, max: 80, step: 1 },
  { key: "lifeExpectancy", category: "PERSONAL", label: "Life Expectancy", description: "Primary life horizon", tooltip: "Extends retirement cash-flow and corpus sustainability modeling.", inputKind: "integer", min: 60, max: 110, step: 1 },
  { key: "spouseLifeExpectancy", category: "PERSONAL", label: "Spouse Life Expectancy", description: "Partner life horizon", tooltip: "Extends household retirement planning for joint goals and withdrawals.", inputKind: "integer", min: 60, max: 110, step: 1 },
  { key: "salaryGrowthRate", category: "INCOME", label: "Salary Growth", description: "Annual salary growth", tooltip: "Expected annual growth rate for salaried income before retirement.", inputKind: "percentage", min: 0, max: 30, step: 0.1 },
  { key: "bonusGrowthRate", category: "INCOME", label: "Bonus Growth", description: "Annual bonus growth", tooltip: "Expected annual growth rate for bonus income streams.", inputKind: "percentage", min: 0, max: 30, step: 0.1 },
  { key: "businessIncomeGrowth", category: "INCOME", label: "Business Income Growth", description: "Annual business growth", tooltip: "Expected growth for entrepreneurial or freelance income.", inputKind: "percentage", min: 0, max: 30, step: 0.1 },
  { key: "rentalIncomeGrowth", category: "INCOME", label: "Rental Income Growth", description: "Annual rental growth", tooltip: "Expected annual increase in rental receipts across properties.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "otherIncomeGrowth", category: "INCOME", label: "Other Income Growth", description: "Annual miscellaneous growth", tooltip: "Used for income sources that do not fit salary, business or rental buckets.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "generalInflation", category: "INFLATION", label: "General Inflation", description: "Baseline inflation", tooltip: "Drives ordinary living expense escalation across the planning horizon.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "medicalInflation", category: "INFLATION", label: "Medical Inflation", description: "Healthcare inflation", tooltip: "Used in late-life planning and health-related stress scenarios.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "educationInflation", category: "INFLATION", label: "Education Inflation", description: "Education cost inflation", tooltip: "Raises future education-goal requirements faster than general inflation.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "lifestyleInflation", category: "INFLATION", label: "Lifestyle Inflation", description: "Lifestyle creep inflation", tooltip: "Captures discretionary spend growth beyond headline inflation.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "propertyInflation", category: "INFLATION", label: "Property Inflation", description: "Property cost inflation", tooltip: "Applied to property-linked expenses and real-estate upkeep assumptions.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "luxuryInflation", category: "INFLATION", label: "Luxury Inflation", description: "Luxury basket inflation", tooltip: "Captures premium lifestyle and aspirational expense inflation.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "equityReturn", category: "INVESTMENTS", label: "Equity Return", description: "Annual equity return", tooltip: "Core public-equity return assumption used in long-range accumulation models.", inputKind: "percentage", min: 0, max: 25, step: 0.1 },
  { key: "debtReturn", category: "INVESTMENTS", label: "Debt Return", description: "Annual debt return", tooltip: "Expected return for fixed income and debt-oriented allocations.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "goldReturn", category: "INVESTMENTS", label: "Gold Return", description: "Annual gold return", tooltip: "Expected appreciation for gold holdings and gold proxies.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "silverReturn", category: "INVESTMENTS", label: "Silver Return", description: "Annual silver return", tooltip: "Expected appreciation for silver holdings and related products.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "realEstateReturn", category: "INVESTMENTS", label: "Real Estate Return", description: "Annual real estate return", tooltip: "Long-run expected return on directly owned property assets.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "cashReturn", category: "INVESTMENTS", label: "Cash Return", description: "Annual cash return", tooltip: "Yield assumption for treasury, savings and surplus cash balances.", inputKind: "percentage", min: 0, max: 15, step: 0.1 },
  { key: "epfReturn", category: "INVESTMENTS", label: "EPF Return", description: "Annual EPF return", tooltip: "Expected declared EPF credit rate used in retirement modeling.", inputKind: "percentage", min: 0, max: 15, step: 0.1 },
  { key: "ppfReturn", category: "INVESTMENTS", label: "PPF Return", description: "Annual PPF return", tooltip: "Expected PPF rate used in tax-advantaged retirement projections.", inputKind: "percentage", min: 0, max: 15, step: 0.1 },
  { key: "npsEquityReturn", category: "INVESTMENTS", label: "NPS Equity Return", description: "Annual NPS equity return", tooltip: "Applied to the equity sleeve of NPS accumulation assumptions.", inputKind: "percentage", min: 0, max: 25, step: 0.1 },
  { key: "npsDebtReturn", category: "INVESTMENTS", label: "NPS Debt Return", description: "Annual NPS debt return", tooltip: "Applied to the debt sleeve of NPS accumulation assumptions.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "homeLoanInterest", category: "LOANS", label: "Home Loan Interest", description: "Annual housing debt rate", tooltip: "Used to assess mortgage drag and refinancing sensitivity.", inputKind: "percentage", min: 0, max: 20, step: 0.1 },
  { key: "carLoanInterest", category: "LOANS", label: "Car Loan Interest", description: "Annual vehicle debt rate", tooltip: "Expected rate for auto-financing obligations.", inputKind: "percentage", min: 0, max: 25, step: 0.1 },
  { key: "personalLoanInterest", category: "LOANS", label: "Personal Loan Interest", description: "Annual personal debt rate", tooltip: "Expected rate for unsecured personal borrowing assumptions.", inputKind: "percentage", min: 0, max: 35, step: 0.1 },
  {
    key: "loanPrepaymentStrategy",
    category: "LOANS",
    label: "Prepayment Strategy",
    description: "Default debt payoff style",
    tooltip: "Sets the assumed household preference for surplus cash deployment against debt.",
    inputKind: "select",
    options: [
      { label: "None", value: "NONE" },
      { label: "Avalanche", value: "AVALANCHE" },
      { label: "Snowball", value: "SNOWBALL" },
      { label: "Hybrid", value: "HYBRID" },
    ],
  },
  { key: "incomeTaxRate", category: "TAXES", label: "Income Tax Rate", description: "Effective income tax", tooltip: "Household blended tax rate for salary and ordinary income planning.", inputKind: "percentage", min: 0, max: 50, step: 0.1 },
  { key: "capitalGainsTax", category: "TAXES", label: "Capital Gains Tax", description: "Effective gains tax", tooltip: "Applied to taxable investment gains in deterministic scenarios.", inputKind: "percentage", min: 0, max: 40, step: 0.1 },
  { key: "dividendTax", category: "TAXES", label: "Dividend Tax", description: "Effective dividend tax", tooltip: "Used in post-tax equity income planning assumptions.", inputKind: "percentage", min: 0, max: 40, step: 0.1 },
  { key: "rentalTaxRate", category: "TAXES", label: "Rental Tax Rate", description: "Effective rental tax", tooltip: "Blended tax drag applied to rental cash-flow assumptions.", inputKind: "percentage", min: 0, max: 40, step: 0.1 },
  { key: "withdrawalRate", category: "RETIREMENT", label: "Withdrawal Rate", description: "Safe withdrawal rate", tooltip: "Target sustainable retirement drawdown rate from long-term assets.", inputKind: "percentage", min: 1, max: 10, step: 0.1 },
  { key: "retirementExpenseRatio", category: "RETIREMENT", label: "Retirement Expense Ratio", description: "Retirement spend ratio", tooltip: "Expected retirement spend as a percent of pre-retirement household lifestyle cost.", inputKind: "percentage", min: 20, max: 150, step: 1 },
  { key: "legacyTarget", category: "RETIREMENT", label: "Legacy Target", description: "Desired legacy corpus", tooltip: "Minimum estate or intergenerational wealth target to preserve at end-of-life.", inputKind: "currency", min: 0, max: 100000000000, step: 100000 },
  { key: "emergencyCorpusMonths", category: "RETIREMENT", label: "Emergency Corpus Months", description: "Liquidity reserve target", tooltip: "Target months of core expenses to maintain as an emergency reserve.", inputKind: "integer", min: 1, max: 60, step: 1 },
] as const;

export function getScenarioRecommendedAssumptions(preset: PlanningScenarioPreset): EffectivePlanningAssumptions {
  return {
    ...SYSTEM_DEFAULT_PLANNING_ASSUMPTIONS,
    ...SCENARIO_PRESET_OVERRIDES[preset],
  };
}
