export {
  getRegistryItem,
  getScenarioRecommendedAssumptions,
  PLANNING_ASSUMPTION_DOCUMENTATION,
  PLANNING_ASSUMPTION_FIELD_DEFINITIONS,
  PLANNING_ASSUMPTION_SECTIONS,
  SCENARIO_PRESET_DESCRIPTIONS,
  SCENARIO_PRESET_OVERRIDES,
  SYSTEM_DEFAULT_PLANNING_ASSUMPTIONS,
} from "./AssumptionRegistry";