import type {
  EffectivePlanningAssumptions,
  PlanningAssumptionDocumentationItem,
  PlanningAssumptionFieldDefinition,
  PlanningAssumptionHelpContent,
  PlanningAssumptionKey,
  PlanningAssumptionRegistryItem,
  PlanningAssumptionSectionDefinition,
  PlanningScenarioPreset,
} from "./AssumptionTypes";

type RawAssumptionRegistryItem = Omit<PlanningAssumptionRegistryItem, "helpContent"> & {
  helpContent?: Partial<PlanningAssumptionHelpContent>;
};

const RAW_ASSUMPTION_REGISTRY: readonly RawAssumptionRegistryItem[] = [
  {
    key: "currentAge",
    category: "PERSONAL",
    label: "Current Age",
    description: "Primary planner age",
    tooltip: "Used to determine time to retirement and remaining compounding horizon.",
    unit: "years",
    inputKind: "integer",
    min: 18,
    max: 100,
    step: 1,
    defaultValue: 35,
    recommendedValue: 35,
    dependencies: ["longevity"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "FAMILY_WEALTH_TIMELINE", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "retirementAge",
    category: "PERSONAL",
    label: "Retirement Age",
    description: "Planned retirement age",
    tooltip: "The assumed age when earned income planning transitions into retirement drawdown.",
    unit: "years",
    inputKind: "integer",
    min: 40,
    max: 80,
    step: 1,
    defaultValue: 60,
    recommendedValue: 60,
    dependencies: ["longevity", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "GOAL_PROBABILITY_ANALYSIS", "FAMILY_WEALTH_TIMELINE", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "lifeExpectancy",
    category: "PERSONAL",
    label: "Life Expectancy",
    description: "Primary life horizon",
    tooltip: "Extends retirement cash-flow and corpus sustainability modeling.",
    unit: "years",
    inputKind: "integer",
    min: 60,
    max: 110,
    step: 1,
    defaultValue: 90,
    recommendedValue: 90,
    dependencies: ["longevity", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "GOAL_PROBABILITY_ANALYSIS", "FAMILY_WEALTH_TIMELINE", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "spouseLifeExpectancy",
    category: "PERSONAL",
    label: "Spouse Life Expectancy",
    description: "Partner life horizon",
    tooltip: "Extends household retirement planning for joint goals and withdrawals.",
    unit: "years",
    inputKind: "integer",
    min: 60,
    max: 110,
    step: 1,
    defaultValue: 92,
    recommendedValue: 92,
    dependencies: ["longevity", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "FAMILY_WEALTH_TIMELINE", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "salaryGrowthRate",
    category: "INCOME",
    label: "Salary Growth",
    description: "Annual salary growth",
    tooltip: "Expected annual growth rate for salaried income before retirement.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 30,
    step: 0.1,
    defaultValue: 8,
    recommendedValue: 8,
    dependencies: ["salary"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "GOAL_PROBABILITY_ANALYSIS", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "bonusGrowthRate",
    category: "INCOME",
    label: "Bonus Growth",
    description: "Annual bonus growth",
    tooltip: "Expected annual growth rate for bonus income streams.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 30,
    step: 0.1,
    defaultValue: 6,
    recommendedValue: 6,
    dependencies: ["salary"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "businessIncomeGrowth",
    category: "INCOME",
    label: "Business Income Growth",
    description: "Annual business growth",
    tooltip: "Expected growth for entrepreneurial or freelance income.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 30,
    step: 0.1,
    defaultValue: 7,
    recommendedValue: 7,
    dependencies: ["salary"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "rentalIncomeGrowth",
    category: "INCOME",
    label: "Rental Income Growth",
    description: "Annual rental growth",
    tooltip: "Expected annual increase in rental receipts across properties.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 5,
    recommendedValue: 5,
    dependencies: ["salary"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "otherIncomeGrowth",
    category: "INCOME",
    label: "Other Income Growth",
    description: "Annual miscellaneous growth",
    tooltip: "Used for income sources that do not fit salary, business or rental buckets.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 4,
    recommendedValue: 4,
    dependencies: ["salary"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING"],
  },
  {
    key: "generalInflation",
    category: "INFLATION",
    label: "General Inflation",
    description: "Baseline inflation",
    tooltip: "Drives ordinary living expense escalation across the planning horizon.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 6,
    recommendedValue: 6,
    dependencies: ["goal-cost-escalation"],
    affectedEngines: ["PROJECTION_ENGINE", "GOAL_PROBABILITY_ANALYSIS", "CASH_FLOW_FORECASTING", "FAMILY_WEALTH_TIMELINE", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "medicalInflation",
    category: "INFLATION",
    label: "Medical Inflation",
    description: "Healthcare inflation",
    tooltip: "Used in late-life planning and health-related stress scenarios.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 9,
    recommendedValue: 9,
    dependencies: ["goal-cost-escalation", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "GOAL_PROBABILITY_ANALYSIS", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "educationInflation",
    category: "INFLATION",
    label: "Education Inflation",
    description: "Education cost inflation",
    tooltip: "Raises future education-goal requirements faster than general inflation.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 10,
    recommendedValue: 10,
    dependencies: ["goal-cost-escalation"],
    affectedEngines: ["PROJECTION_ENGINE", "GOAL_PROBABILITY_ANALYSIS", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "lifestyleInflation",
    category: "INFLATION",
    label: "Lifestyle Inflation",
    description: "Lifestyle creep inflation",
    tooltip: "Captures discretionary spend growth beyond headline inflation.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 7,
    recommendedValue: 7,
    dependencies: ["goal-cost-escalation", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "CASH_FLOW_FORECASTING", "FAMILY_WEALTH_TIMELINE"],
  },
  {
    key: "propertyInflation",
    category: "INFLATION",
    label: "Property Inflation",
    description: "Property cost inflation",
    tooltip: "Applied to property-linked expenses and real-estate upkeep assumptions.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 5,
    recommendedValue: 5,
    dependencies: ["goal-cost-escalation"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING"],
  },
  {
    key: "luxuryInflation",
    category: "INFLATION",
    label: "Luxury Inflation",
    description: "Luxury basket inflation",
    tooltip: "Captures premium lifestyle and aspirational expense inflation.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 8,
    recommendedValue: 8,
    dependencies: ["goal-cost-escalation"],
    affectedEngines: ["PROJECTION_ENGINE", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "equityReturn",
    category: "INVESTMENTS",
    label: "Equity Return",
    description: "Annual equity return",
    tooltip: "Core public-equity return assumption used in long-range accumulation models.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 25,
    step: 0.1,
    defaultValue: 12,
    recommendedValue: 12,
    dependencies: ["asset-return"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "GOAL_PROBABILITY_ANALYSIS", "FAMILY_WEALTH_TIMELINE", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "debtReturn",
    category: "INVESTMENTS",
    label: "Debt Return",
    description: "Annual debt return",
    tooltip: "Expected return for fixed income and debt-oriented allocations.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 7,
    recommendedValue: 7,
    dependencies: ["asset-return"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "GOAL_PROBABILITY_ANALYSIS"],
  },
  {
    key: "goldReturn",
    category: "INVESTMENTS",
    label: "Gold Return",
    description: "Annual gold return",
    tooltip: "Expected appreciation for gold holdings and gold proxies.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 6,
    recommendedValue: 6,
    dependencies: ["asset-return"],
    affectedEngines: ["PROJECTION_ENGINE", "GOAL_PROBABILITY_ANALYSIS", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "silverReturn",
    category: "INVESTMENTS",
    label: "Silver Return",
    description: "Annual silver return",
    tooltip: "Expected appreciation for silver holdings and related products.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 5,
    recommendedValue: 5,
    dependencies: ["asset-return"],
    affectedEngines: ["PROJECTION_ENGINE", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "realEstateReturn",
    category: "INVESTMENTS",
    label: "Real Estate Return",
    description: "Annual real estate return",
    tooltip: "Long-run expected return on directly owned property assets.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 8,
    recommendedValue: 8,
    dependencies: ["asset-return"],
    affectedEngines: ["PROJECTION_ENGINE", "GOAL_PROBABILITY_ANALYSIS", "FAMILY_WEALTH_TIMELINE", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "cashReturn",
    category: "INVESTMENTS",
    label: "Cash Return",
    description: "Annual cash return",
    tooltip: "Yield assumption for treasury, savings and surplus cash balances.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 15,
    step: 0.1,
    defaultValue: 4,
    recommendedValue: 4,
    dependencies: ["asset-return", "liquidity-buffer"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "epfReturn",
    category: "INVESTMENTS",
    label: "EPF Return",
    description: "Annual EPF return",
    tooltip: "Expected declared EPF credit rate used in retirement modeling.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 15,
    step: 0.1,
    defaultValue: 8.15,
    recommendedValue: 8.15,
    dependencies: ["asset-return", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "FAMILY_WEALTH_TIMELINE"],
  },
  {
    key: "ppfReturn",
    category: "INVESTMENTS",
    label: "PPF Return",
    description: "Annual PPF return",
    tooltip: "Expected PPF rate used in tax-advantaged retirement projections.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 15,
    step: 0.1,
    defaultValue: 7.1,
    recommendedValue: 7.1,
    dependencies: ["asset-return", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING"],
  },
  {
    key: "npsEquityReturn",
    category: "INVESTMENTS",
    label: "NPS Equity Return",
    description: "Annual NPS equity return",
    tooltip: "Applied to the equity sleeve of NPS accumulation assumptions.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 25,
    step: 0.1,
    defaultValue: 11,
    recommendedValue: 11,
    dependencies: ["asset-return", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "npsDebtReturn",
    category: "INVESTMENTS",
    label: "NPS Debt Return",
    description: "Annual NPS debt return",
    tooltip: "Applied to the debt sleeve of NPS accumulation assumptions.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 7,
    recommendedValue: 7,
    dependencies: ["asset-return", "retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING"],
  },
  {
    key: "homeLoanInterest",
    category: "LOANS",
    label: "Home Loan Interest",
    description: "Annual housing debt rate",
    tooltip: "Used to assess mortgage drag and refinancing sensitivity.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 20,
    step: 0.1,
    defaultValue: 8.5,
    recommendedValue: 8.5,
    dependencies: ["debt-cost"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "AI_FINANCIAL_ADVISOR", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "carLoanInterest",
    category: "LOANS",
    label: "Car Loan Interest",
    description: "Annual vehicle debt rate",
    tooltip: "Expected rate for auto-financing obligations.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 25,
    step: 0.1,
    defaultValue: 9.5,
    recommendedValue: 9.5,
    dependencies: ["debt-cost"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING"],
  },
  {
    key: "personalLoanInterest",
    category: "LOANS",
    label: "Personal Loan Interest",
    description: "Annual personal debt rate",
    tooltip: "Expected rate for unsecured personal borrowing assumptions.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 35,
    step: 0.1,
    defaultValue: 13,
    recommendedValue: 13,
    dependencies: ["debt-cost"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "loanPrepaymentStrategy",
    category: "LOANS",
    label: "Prepayment Strategy",
    description: "Default debt payoff style",
    tooltip: "Sets the assumed household preference for surplus cash deployment against debt.",
    unit: "strategy",
    inputKind: "select",
    options: [
      { label: "None", value: "NONE" },
      { label: "Avalanche", value: "AVALANCHE" },
      { label: "Snowball", value: "SNOWBALL" },
      { label: "Hybrid", value: "HYBRID" },
    ],
    defaultValue: "HYBRID",
    recommendedValue: "HYBRID",
    dependencies: ["debt-cost", "liquidity-buffer"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "incomeTaxRate",
    category: "TAXES",
    label: "Income Tax Rate",
    description: "Effective income tax",
    tooltip: "Household blended tax rate for salary and ordinary income planning.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 50,
    step: 0.1,
    defaultValue: 20,
    recommendedValue: 20,
    dependencies: ["tax-drag"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "capitalGainsTax",
    category: "TAXES",
    label: "Capital Gains Tax",
    description: "Effective gains tax",
    tooltip: "Applied to taxable investment gains in deterministic scenarios.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 40,
    step: 0.1,
    defaultValue: 10,
    recommendedValue: 10,
    dependencies: ["tax-drag"],
    affectedEngines: ["PROJECTION_ENGINE", "GOAL_PROBABILITY_ANALYSIS", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "dividendTax",
    category: "TAXES",
    label: "Dividend Tax",
    description: "Effective dividend tax",
    tooltip: "Used in post-tax equity income planning assumptions.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 40,
    step: 0.1,
    defaultValue: 10,
    recommendedValue: 10,
    dependencies: ["tax-drag"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING"],
  },
  {
    key: "rentalTaxRate",
    category: "TAXES",
    label: "Rental Tax Rate",
    description: "Effective rental tax",
    tooltip: "Blended tax drag applied to rental cash-flow assumptions.",
    unit: "percent",
    inputKind: "percentage",
    min: 0,
    max: 40,
    step: 0.1,
    defaultValue: 20,
    recommendedValue: 20,
    dependencies: ["tax-drag"],
    affectedEngines: ["PROJECTION_ENGINE", "CASH_FLOW_FORECASTING"],
  },
  {
    key: "withdrawalRate",
    category: "RETIREMENT",
    label: "Withdrawal Rate",
    description: "Safe withdrawal rate",
    tooltip: "Target sustainable retirement drawdown rate from long-term assets.",
    unit: "percent",
    inputKind: "percentage",
    min: 1,
    max: 10,
    step: 0.1,
    defaultValue: 4,
    recommendedValue: 4,
    dependencies: ["retirement-corpus"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "GOAL_PROBABILITY_ANALYSIS", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "retirementExpenseRatio",
    category: "RETIREMENT",
    label: "Retirement Expense Ratio",
    description: "Retirement spend ratio",
    tooltip: "Expected retirement spend as a percent of pre-retirement household lifestyle cost.",
    unit: "percent",
    inputKind: "percentage",
    min: 20,
    max: 150,
    step: 1,
    defaultValue: 85,
    recommendedValue: 85,
    dependencies: ["retirement-corpus", "goal-cost-escalation"],
    affectedEngines: ["PROJECTION_ENGINE", "RETIREMENT_PLANNING", "FAMILY_WEALTH_TIMELINE"],
  },
  {
    key: "legacyTarget",
    category: "RETIREMENT",
    label: "Legacy Target",
    description: "Desired legacy corpus",
    tooltip: "Minimum estate or intergenerational wealth target to preserve at end-of-life.",
    unit: "currency",
    inputKind: "currency",
    min: 0,
    max: 100000000000,
    step: 100000,
    defaultValue: 0,
    recommendedValue: 0,
    dependencies: ["retirement-corpus"],
    affectedEngines: ["RETIREMENT_PLANNING", "FAMILY_WEALTH_TIMELINE", "AI_FINANCIAL_ADVISOR"],
  },
  {
    key: "emergencyCorpusMonths",
    category: "RETIREMENT",
    label: "Emergency Corpus Months",
    description: "Liquidity reserve target",
    tooltip: "Target months of core expenses to maintain as an emergency reserve.",
    unit: "months",
    inputKind: "integer",
    min: 1,
    max: 60,
    step: 1,
    defaultValue: 12,
    recommendedValue: 12,
    dependencies: ["liquidity-buffer"],
    affectedEngines: ["RETIREMENT_PLANNING", "CASH_FLOW_FORECASTING", "EXECUTIVE_DASHBOARD"],
  },
  {
    key: "goalFundingPriority",
    category: "RETIREMENT",
    label: "Goal Funding Priority",
    description: "Default funding priority",
    tooltip: "Used by goal-level overrides when no explicit priority is provided on the goal itself.",
    unit: "priority",
    inputKind: "select",
    options: [
      { label: "Low", value: "LOW" },
      { label: "Medium", value: "MEDIUM" },
      { label: "High", value: "HIGH" },
    ],
    defaultValue: "MEDIUM",
    recommendedValue: "MEDIUM",
    dependencies: ["goal-cost-escalation"],
    affectedEngines: ["GOAL_PROBABILITY_ANALYSIS", "AI_FINANCIAL_ADVISOR"],
  },
] as const;

function formatUnitLabel(item: { unit: PlanningAssumptionRegistryItem["unit"] }) {
  if (item.unit === "percent") {
    return "%";
  }

  if (item.unit === "currency") {
    return "currency";
  }

  return item.unit;
}

function formatRecommendedRange(item: Pick<PlanningAssumptionRegistryItem, "min" | "max" | "unit">) {
  const unit = formatUnitLabel(item);
  if (typeof item.min === "number" && typeof item.max === "number") {
    return `${item.min} to ${item.max} ${unit}`;
  }

  if (typeof item.min === "number") {
    return `At least ${item.min} ${unit}`;
  }

  if (typeof item.max === "number") {
    return `Up to ${item.max} ${unit}`;
  }

  return "Use the suggested system baseline for your profile.";
}

function formatDefaultValue(item: Pick<PlanningAssumptionRegistryItem, "defaultValue" | "unit">) {
  const unit = formatUnitLabel(item);
  return `${String(item.defaultValue)} ${unit}`;
}

function buildExampleCalculation(item: Pick<PlanningAssumptionRegistryItem, "inputKind" | "label" | "recommendedValue" | "unit">) {
  if (item.inputKind === "percentage") {
    return `If ${item.label} is ${item.recommendedValue}%, a base value of 100 becomes ${100 + Number(item.recommendedValue)} after one year.`;
  }

  if (item.inputKind === "currency") {
    return `A target of ${item.recommendedValue} means plans will reserve at least that amount in absolute currency terms.`;
  }

  if (item.inputKind === "integer" && item.unit === "years") {
    return `Setting ${item.label} to ${item.recommendedValue} adjusts the projection horizon and timeline milestones.`;
  }

  return undefined;
}

function buildSensitivityText(item: Pick<PlanningAssumptionRegistryItem, "category" | "label">) {
  const categoryLabel = item.category.toLowerCase();

  return {
    increase: `Increasing ${item.label} generally raises modeled impact in ${categoryLabel} planning outcomes and can change goal feasibility timelines.`,
    decrease: `Decreasing ${item.label} generally lowers modeled impact in ${categoryLabel} planning outcomes and may require offsetting assumptions elsewhere.`,
  };
}

function buildHelpContent(item: RawAssumptionRegistryItem): PlanningAssumptionHelpContent {
  const sensitivity = buildSensitivityText(item);

  return {
    shortDescription: item.helpContent?.shortDescription ?? item.description,
    detailedExplanation: item.helpContent?.detailedExplanation ?? item.tooltip,
    whyItMatters:
      item.helpContent?.whyItMatters ??
      `${item.label} is used by ${item.affectedEngines.length} planning engines and impacts downstream scenario calculations.`,
    recommendedRange: item.helpContent?.recommendedRange ?? formatRecommendedRange(item),
    defaultValue: item.helpContent?.defaultValue ?? formatDefaultValue(item),
    exampleCalculation: item.helpContent?.exampleCalculation ?? buildExampleCalculation(item),
    effectOfIncrease: item.helpContent?.effectOfIncrease ?? sensitivity.increase,
    effectOfDecrease: item.helpContent?.effectOfDecrease ?? sensitivity.decrease,
  };
}

export const ASSUMPTION_REGISTRY: readonly PlanningAssumptionRegistryItem[] = RAW_ASSUMPTION_REGISTRY.map((item) => ({
  ...item,
  helpContent: buildHelpContent(item),
}));

const SECTION_ORDER: ReadonlyArray<PlanningAssumptionSectionDefinition["category"]> = [
  "PERSONAL",
  "INCOME",
  "INFLATION",
  "INVESTMENTS",
  "LOANS",
  "TAXES",
  "RETIREMENT",
];

const SECTION_DESCRIPTIONS: Record<PlanningAssumptionSectionDefinition["category"], { label: string; description: string }> = {
  PERSONAL: { label: "Personal", description: "Longevity and retirement horizon inputs that shape every future plan." },
  INCOME: { label: "Income", description: "Growth assumptions for earned, business, rental and supplemental income streams." },
  INFLATION: { label: "Inflation", description: "Category-specific inflation expectations used across lifestyle and goal planning." },
  INVESTMENTS: { label: "Investments", description: "Long-run expected returns for liquid, retirement and real assets." },
  LOANS: { label: "Loans", description: "Borrowing cost and repayment-policy assumptions for debt-sensitive planning." },
  TAXES: { label: "Taxes", description: "Effective tax assumptions for income, capital gains, dividends and rental cash flow." },
  RETIREMENT: { label: "Retirement", description: "Withdrawal discipline, target spending, legacy planning and emergency corpus assumptions." },
};

export const PLANNING_ASSUMPTION_SECTIONS: readonly PlanningAssumptionSectionDefinition[] = SECTION_ORDER.map((category) => ({
  category,
  label: SECTION_DESCRIPTIONS[category].label,
  description: SECTION_DESCRIPTIONS[category].description,
  fieldKeys: ASSUMPTION_REGISTRY.filter((item) => item.category === category && item.key !== "currentAge").map((item) => item.key),
}));

export const PLANNING_ASSUMPTION_FIELD_DEFINITIONS: readonly PlanningAssumptionFieldDefinition[] = ASSUMPTION_REGISTRY
  .filter((item) => item.key !== "currentAge")
  .map(({ defaultValue: _defaultValue, recommendedValue: _recommendedValue, dependencies: _dependencies, affectedEngines: _affectedEngines, ...definition }) => definition);

export const SYSTEM_DEFAULT_PLANNING_ASSUMPTIONS: EffectivePlanningAssumptions = ASSUMPTION_REGISTRY.reduce<EffectivePlanningAssumptions>(
  (accumulator, item) => ({
    ...accumulator,
    [item.key]: item.defaultValue,
  }),
  {} as EffectivePlanningAssumptions,
);

export const PLANNING_ASSUMPTION_DOCUMENTATION: readonly PlanningAssumptionDocumentationItem[] = ASSUMPTION_REGISTRY.map((item) => ({
  key: item.key,
  label: item.label,
  category: item.category,
  description: item.description,
  tooltip: item.tooltip,
  helpContent: item.helpContent,
  unit: item.unit,
  dependencies: item.dependencies,
  affectedEngines: item.affectedEngines,
}));

export const SCENARIO_PRESET_DESCRIPTIONS: Record<PlanningScenarioPreset, string> = {
  BASE: "Balanced planning assumptions aligned to the system baseline.",
  CONSERVATIVE: "Lower return assumptions and higher stress-case inflation inputs.",
  OPTIMISTIC: "Higher growth expectations with milder inflation pressure.",
  CUSTOM: "A fully customizable scenario inheriting from your user defaults.",
};

export const SCENARIO_PRESET_OVERRIDES: Record<PlanningScenarioPreset, Partial<EffectivePlanningAssumptions>> = {
  BASE: {},
  CONSERVATIVE: {
    salaryGrowthRate: 6,
    bonusGrowthRate: 4,
    businessIncomeGrowth: 5,
    rentalIncomeGrowth: 4,
    otherIncomeGrowth: 3,
    generalInflation: 7,
    medicalInflation: 10,
    educationInflation: 11,
    lifestyleInflation: 8,
    propertyInflation: 4,
    luxuryInflation: 9,
    equityReturn: 9,
    debtReturn: 6.5,
    goldReturn: 5.5,
    silverReturn: 4.5,
    realEstateReturn: 6.5,
    cashReturn: 4.5,
    epfReturn: 7.75,
    ppfReturn: 7,
    npsEquityReturn: 9,
    npsDebtReturn: 6.5,
    withdrawalRate: 3.5,
    retirementExpenseRatio: 95,
    emergencyCorpusMonths: 18,
  },
  OPTIMISTIC: {
    salaryGrowthRate: 10,
    bonusGrowthRate: 8,
    businessIncomeGrowth: 10,
    rentalIncomeGrowth: 6,
    otherIncomeGrowth: 5,
    generalInflation: 5,
    medicalInflation: 8,
    educationInflation: 8,
    lifestyleInflation: 6,
    propertyInflation: 6,
    luxuryInflation: 7,
    equityReturn: 14,
    debtReturn: 7.5,
    goldReturn: 7,
    silverReturn: 6.5,
    realEstateReturn: 9,
    epfReturn: 8.4,
    ppfReturn: 7.3,
    npsEquityReturn: 13,
    npsDebtReturn: 7.5,
    withdrawalRate: 5,
    retirementExpenseRatio: 80,
    emergencyCorpusMonths: 9,
  },
  CUSTOM: {},
};

export function getScenarioRecommendedAssumptions(preset: PlanningScenarioPreset): EffectivePlanningAssumptions {
  return {
    ...SYSTEM_DEFAULT_PLANNING_ASSUMPTIONS,
    ...SCENARIO_PRESET_OVERRIDES[preset],
  };
}

export function getRegistryItem(key: PlanningAssumptionKey) {
  const item = ASSUMPTION_REGISTRY.find((registryItem) => registryItem.key === key);
  if (!item) {
    throw new Error(`Missing planning assumption registry entry for ${key}.`);
  }

  return item;
}