import { FormulaCatalog } from "./FormulaCatalog";
import type { FormulaReference } from "./FormulaReference";
import { formulaValidator, type FormulaValidationIssue } from "./FormulaValidator";
import type { FormulaMetadata } from "./FormulaMetadata";

const DEFAULT_FORMULAS: FormulaMetadata[] = [
  {
    formulaId: "NW-001",
    module: "finance",
    description: "Net Worth = Assets - Liabilities.",
    excelEquivalent: "=SUM(Assets)-SUM(Liabilities)",
    formulaExpression: "SUM(Assets) - SUM(Liabilities)",
    version: "1",
    effectiveDate: "2026-07-26",
    owner: "WealthOS",
    exampleInput: "Assets=1250000, Liabilities=450000",
    exampleOutput: "Net Worth=800000",
    validationStatus: "Validated",
  },
  {
    formulaId: "AS-001",
    module: "finance",
    description: "Total asset value.",
    excelEquivalent: "=SUM(AssetValues)",
    formulaExpression: "SUM(AssetValues)",
    version: "1",
    effectiveDate: "2026-07-26",
    owner: "WealthOS",
    exampleInput: "AssetValues=[500000,250000,100000]",
    exampleOutput: "Assets=850000",
    validationStatus: "Validated",
  },
  {
    formulaId: "LI-001",
    module: "finance",
    description: "Total liabilities value.",
    excelEquivalent: "=SUM(LiabilityBalances)",
    formulaExpression: "SUM(LiabilityBalances)",
    version: "1",
    effectiveDate: "2026-07-26",
    owner: "WealthOS",
    exampleInput: "LiabilityBalances=[250000,200000]",
    exampleOutput: "Liabilities=450000",
    validationStatus: "Validated",
  },
  {
    formulaId: "EMI-001",
    module: "finance",
    description: "Monthly EMI obligation total.",
    excelEquivalent: "=SUM(EMIAmounts)",
    formulaExpression: "SUM(EMIAmounts)",
    version: "1",
    effectiveDate: "2026-07-26",
    owner: "WealthOS",
    exampleInput: "EMIAmounts=[12000,8000]",
    exampleOutput: "Monthly EMI=20000",
    validationStatus: "Validated",
  },
  {
    formulaId: "INV-001",
    module: "finance",
    description: "Aggregate investment value.",
    excelEquivalent: "=SUM(CurrentInvestmentValues)",
    formulaExpression: "SUM(CurrentInvestmentValues)",
    version: "1",
    effectiveDate: "2026-07-26",
    owner: "WealthOS",
    exampleInput: "CurrentInvestmentValues=[250000,175000,50000]",
    exampleOutput: "Investments=475000",
    validationStatus: "Validated",
  },
  {
    formulaId: "CASH-001",
    module: "finance",
    description: "Liquid cash holdings across assets and investments.",
    excelEquivalent: "=SUM(CashAssets)+SUM(CashInvestments)",
    formulaExpression: "SUM(CashAssets) + SUM(CashInvestments)",
    version: "1",
    effectiveDate: "2026-07-26",
    owner: "WealthOS",
    exampleInput: "CashAssets=[100000], CashInvestments=[50000]",
    exampleOutput: "Cash Holdings=150000",
    validationStatus: "Validated",
  },
  {
    formulaId: "DR-001",
    module: "finance",
    description: "Debt ratio = liabilities / assets.",
    excelEquivalent: "=IF(Assets<=0,0,Liabilities/Assets)",
    formulaExpression: "IF(Assets <= 0, 0, Liabilities / Assets)",
    version: "1",
    effectiveDate: "2026-07-26",
    owner: "WealthOS",
    exampleInput: "Assets=1250000, Liabilities=450000",
    exampleOutput: "Debt Ratio=0.36",
    validationStatus: "Validated",
  },
  {
    formulaId: "INC-SALARY-ANNUAL-INCREMENT",
    module: "planning-income",
    description: "Monthly salary with annual increment applied on configured increment month.",
    excelEquivalent: "=(SalaryAnnual/12) * POWER(1+IncrementRate, IncrementsElapsed)",
    formulaExpression: "(SalaryAnnual / 12) * POWER(1 + IncrementRate, IncrementsElapsed)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "SalaryAnnual=1200000, IncrementRate=0.08, IncrementsElapsed=2",
    exampleOutput: "Monthly Salary=108000",
    validationStatus: "Validated",
  },
  {
    formulaId: "INC-BONUS-MONTH",
    module: "planning-income",
    description: "Annual bonus paid in configured bonus month while working.",
    excelEquivalent: "=IF(Month=BonusMonth, BonusAnnual, 0)",
    formulaExpression: "IF(Month = BonusMonth, BonusAnnual, 0)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "Month=12, BonusMonth=12, BonusAnnual=200000",
    exampleOutput: "Bonus=200000",
    validationStatus: "Validated",
  },
  {
    formulaId: "INC-RENTAL-ESCALATION",
    module: "planning-income",
    description: "Monthly rental income escalated annually on configured month.",
    excelEquivalent: "=(RentalAnnual/12) * POWER(1+EscalationRate, EscalationsElapsed)",
    formulaExpression: "(RentalAnnual / 12) * POWER(1 + EscalationRate, EscalationsElapsed)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "RentalAnnual=240000, EscalationRate=0.05, EscalationsElapsed=1",
    exampleOutput: "Monthly Rental=21000",
    validationStatus: "Validated",
  },
  {
    formulaId: "EXP-INFLATION-ESCALATION",
    module: "planning-expense",
    description: "Monthly expense category escalated annually using category inflation rate.",
    excelEquivalent: "=BaseMonthly * POWER(1+InflationRate, EscalationsElapsed)",
    formulaExpression: "BaseMonthly * POWER(1 + InflationRate, EscalationsElapsed)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "BaseMonthly=50000, InflationRate=0.06, EscalationsElapsed=2",
    exampleOutput: "Escalated Expense=56180",
    validationStatus: "Validated",
  },
  {
    formulaId: "EXP-FREQUENCY-SCHEDULE",
    module: "planning-expense",
    description: "Event expense scheduling by monthly, quarterly, annual, or one-time frequency.",
    excelEquivalent: "=IF(FrequencyMatch, Amount, 0)",
    formulaExpression: "IF(FrequencyMatch, Amount, 0)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "Frequency=Quarterly, Amount=15000, MonthMatch=TRUE",
    exampleOutput: "Scheduled Expense=15000",
    validationStatus: "Validated",
  },
  {
    formulaId: "EXP-RETIREMENT-RATIO",
    module: "planning-expense",
    description: "Retirement expense load as ratio of pre-retirement subtotal.",
    excelEquivalent: "=PreRetirementSubtotal * RetirementExpenseRatio",
    formulaExpression: "PreRetirementSubtotal * RetirementExpenseRatio",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "PreRetirementSubtotal=120000, RetirementExpenseRatio=0.75",
    exampleOutput: "Retirement Expenses=90000",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-SALARY-STOP-RETIREMENT",
    module: "planning-rules",
    description: "Salary stops after retirement.",
    excelEquivalent: "=IF(RetirementFlag, TRUE, FALSE)",
    formulaExpression: "IF(RetirementFlag, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "RetirementFlag=TRUE",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-SALARY-INCREMENT-MONTH",
    module: "planning-rules",
    description: "Salary increment month.",
    excelEquivalent: "=IF(Month=IncrementMonth, TRUE, FALSE)",
    formulaExpression: "IF(Month = IncrementMonth, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "Month=4, IncrementMonth=4",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-BONUS-MONTH",
    module: "planning-rules",
    description: "Bonus month.",
    excelEquivalent: "=IF(Month=BonusMonth, TRUE, FALSE)",
    formulaExpression: "IF(Month = BonusMonth, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "Month=12, BonusMonth=12",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-EPF-WHILE-EMPLOYED",
    module: "planning-rules",
    description: "EPF only while employed.",
    excelEquivalent: "=IF(EmploymentStatus=\"EMPLOYED\", TRUE, FALSE)",
    formulaExpression: "IF(EmploymentStatus = \"EMPLOYED\", TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "EmploymentStatus=EMPLOYED",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-PPF-MATURITY-15Y",
    module: "planning-rules",
    description: "PPF matures after 15 years.",
    excelEquivalent: "=IF(YearsElapsed>=15, TRUE, FALSE)",
    formulaExpression: "IF(YearsElapsed >= 15, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "YearsElapsed=15",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-NPS-EMPLOYMENT-START",
    module: "planning-rules",
    description: "NPS starts at employment.",
    excelEquivalent: "=IF(EmploymentStartMonth<=ProjectionMonth, TRUE, FALSE)",
    formulaExpression: "IF(EmploymentStartMonth <= ProjectionMonth, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "EmploymentStartMonth=2026-01, ProjectionMonth=2026-03",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-EMI-FORECLOSURE",
    module: "planning-rules",
    description: "EMI ends after foreclosure.",
    excelEquivalent: "=IF(Foreclosed, FALSE, TRUE)",
    formulaExpression: "IF(Foreclosed, FALSE, TRUE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "Foreclosed=FALSE",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-INSURANCE-RENEWAL-MONTH",
    module: "planning-rules",
    description: "Insurance renewal month.",
    excelEquivalent: "=IF(Month=RenewalMonth, TRUE, FALSE)",
    formulaExpression: "IF(Month = RenewalMonth, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "Month=4, RenewalMonth=4",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-VACATION-DECEMBER",
    module: "planning-rules",
    description: "Vacation expense every December.",
    excelEquivalent: "=IF(Month=12, TRUE, FALSE)",
    formulaExpression: "IF(Month = 12, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "Month=12",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-EDUCATION-UNTIL-GRADUATION",
    module: "planning-rules",
    description: "Education expense until graduation.",
    excelEquivalent: "=IF(ProjectionMonth<=GraduationMonth, TRUE, FALSE)",
    formulaExpression: "IF(ProjectionMonth <= GraduationMonth, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "ProjectionMonth=2026-05, GraduationMonth=2026-12",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-GOAL-FUNDING-TRIGGER",
    module: "planning-rules",
    description: "Goal funding only after trigger.",
    excelEquivalent: "=IF(TriggerReached, TRUE, FALSE)",
    formulaExpression: "IF(TriggerReached, TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "TriggerReached=TRUE",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
  {
    formulaId: "RULE-TAX-REGIME-SELECTION",
    module: "planning-rules",
    description: "Tax regime selection.",
    excelEquivalent: "=IF(TaxRegimeSelected<>\"\", TRUE, FALSE)",
    formulaExpression: "IF(TaxRegimeSelected <> \"\", TRUE, FALSE)",
    version: "1.0.0",
    effectiveDate: "2026-07-26",
    owner: "WealthOS Planning",
    exampleInput: "TaxRegimeSelected=NEW",
    exampleOutput: "Applied=TRUE",
    validationStatus: "Validated",
  },
];

export class FormulaRegistry {
  private readonly catalog: FormulaCatalog;

  constructor(catalog: FormulaCatalog = new FormulaCatalog(DEFAULT_FORMULAS)) {
    this.catalog = catalog;
  }

  get(formulaId: string): FormulaMetadata {
    return this.catalog.get(formulaId);
  }

  has(formulaId: string): boolean {
    return this.catalog.has(formulaId);
  }

  list(): FormulaMetadata[] {
    return this.catalog.list();
  }

  listByModule(module: string): FormulaMetadata[] {
    return this.catalog.listByModule(module);
  }

  reference(formulaId: string): FormulaReference {
    return this.catalog.reference(formulaId);
  }

  validateReference(reference: FormulaReference): FormulaValidationIssue[] {
    return formulaValidator.validateReference(reference, this.catalog.list());
  }

  validateCatalog(): FormulaValidationIssue[] {
    return formulaValidator.validateCatalog(this.catalog.list());
  }
}

export const formulaRegistry = new FormulaRegistry();
