import * as XLSX from "xlsx";

interface ImportTemplateSheetDefinition {
  sheetName: string;
  headers: string[];
  sampleRow: Array<string | number | boolean | null>;
}

const importTemplateSheets: ImportTemplateSheetDefinition[] = [
  {
    sheetName: "Bank Accounts",
    headers: [
      "Bank Name",
      "Account Name",
      "Account Number",
      "Latest Balance",
      "Opening Balance",
      "Account Type",
      "Status",
      "Currency",
      "Interest Rate",
      "Owner",
      "Nominee",
      "IFSC",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "HDFC Bank",
      "Salary Account",
      "1234567890",
      250000,
      200000,
      "Salary",
      "active",
      "INR",
      3.5,
      "Priyesh",
      "Spouse",
      "HDFC0000123",
      "Primary salary account",
      null,
    ],
  },
  {
    sheetName: "MF Holdings",
    headers: [
      "Investment Name",
      "Category",
      "Owner",
      "Nominee",
      "Folio Number",
      "AMFI Scheme Code",
      "Investment Mode",
      "Option Type",
      "Broker Platform",
      "Units",
      "NAV Price",
      "Cost Basis",
      "SIP Amount",
      "SIP Date",
      "Region",
      "Purchase Date",
      "Today Gain Loss",
      "Sector",
      "AMC",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "HDFC Flexi Cap Fund",
      "Mutual Funds",
      "Priyesh",
      "Spouse",
      "1234567/89",
      "120503",
      "Direct",
      "Growth",
      "Groww",
      1250.75,
      72.35,
      78000,
      5000,
      5,
      "Domestic",
      "2024-04-15",
      320,
      "Diversified",
      "HDFC AMC",
      "SIP holding",
      null,
    ],
  },
  {
    sheetName: "Stock Holdings",
    headers: [
      "Investment Name",
      "Category",
      "Units",
      "NAV Price",
      "Cost Basis",
      "Region",
      "Purchase Date",
      "Today Gain Loss",
      "Sector",
      "AMC",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "TCS",
      "Stocks",
      24,
      4120,
      86500,
      "Domestic",
      "2023-11-02",
      450,
      "IT",
      "Direct",
      "Long-term core equity",
      null,
    ],
  },
  {
    sheetName: "PPF Accounts",
    headers: [
      "Account Type",
      "Institution",
      "Account Number",
      "Holder Name",
      "Current Value",
      "Opening Date",
      "Monthly Contribution",
      "Annual Contribution",
      "Interest Rate",
      "Nominee",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "PPF",
      "State Bank of India",
      "PPF123456",
      "Priyesh",
      545000,
      "2018-05-01",
      null,
      150000,
      7.1,
      "Spouse",
      "PPF long-term corpus",
      null,
    ],
  },
  {
    sheetName: "Loan Inputs",
    headers: [
      "Liability Type",
      "Lender",
      "Account Name",
      "Outstanding Amount",
      "Original Amount",
      "Interest Rate",
      "EMI",
      "Start Date",
      "End Date",
      "Due Day",
      "Status",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "Home Loan",
      "ICICI Bank",
      "Primary Home Loan",
      3450000,
      4200000,
      8.4,
      38250,
      "2021-02-10",
      "2041-02-10",
      5,
      "active",
      "Floating ROI",
      null,
    ],
  },
  {
    sheetName: "Health Insurance",
    headers: [
      "Policy Name",
      "Provider",
      "Owner",
      "Nominee",
      "Status",
      "Opening Value",
      "Current Value",
      "Start Date",
      "Maturity Date",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "Family Floater",
      "Star Health",
      "Priyesh",
      "Spouse",
      "active",
      2000000,
      2000000,
      "2025-01-01",
      "2025-12-31",
      "Annual family floater cover",
      null,
    ],
  },
  {
    sheetName: "Life Insurance",
    headers: [
      "Policy Name",
      "Provider",
      "Owner",
      "Nominee",
      "Status",
      "Opening Value",
      "Current Value",
      "Start Date",
      "Maturity Date",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "Term Life Cover",
      "LIC",
      "Priyesh",
      "Spouse",
      "active",
      10000000,
      10000000,
      "2022-08-01",
      "2052-08-01",
      "Pure term plan",
      null,
    ],
  },
  {
    sheetName: "Fixed Deposits",
    headers: [
      "Deposit Type",
      "Institution",
      "Account Number",
      "Holder",
      "Principal",
      "Interest Rate",
      "Current Value",
      "Compounding Frequency",
      "Opening Date",
      "Maturity Date",
      "Auto Renew",
      "Branch",
      "Owner",
      "Nominee",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "FD",
      "Axis Bank",
      "FD987654",
      "Priyesh",
      500000,
      7.35,
      546200,
      "quarterly",
      "2023-06-15",
      "2026-06-15",
      true,
      "Bangalore Main",
      "Priyesh",
      "Spouse",
      "3-year FD",
      null,
    ],
  },
  {
    sheetName: "Gold",
    headers: [
      "Holding Type",
      "Description",
      "Quantity",
      "Unit",
      "Cost Basis",
      "Current Value",
      "Purchase Date",
      "Purity",
      "Custodian",
      "Institution",
      "Owner",
      "Nominee",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "Physical Gold",
      "22K coins",
      120,
      "g",
      650000,
      810000,
      "2020-10-20",
      "22K",
      "Home Locker",
      null,
      "Priyesh",
      "Spouse",
      "Festival purchases",
      null,
    ],
  },
  {
    sheetName: "Silver",
    headers: [
      "Holding Type",
      "Description",
      "Quantity",
      "Unit",
      "Cost Basis",
      "Current Value",
      "Purchase Date",
      "Purity",
      "Custodian",
      "Institution",
      "Owner",
      "Nominee",
      "Notes",
      "ID",
    ],
    sampleRow: [
      "Physical Silver",
      "Silver bars",
      1500,
      "g",
      98000,
      124000,
      "2021-07-05",
      "999",
      "Home Locker",
      null,
      "Priyesh",
      "Spouse",
      "Hedge allocation",
      null,
    ],
  },
];

function createTemplateWorkbook() {
  const workbook = XLSX.utils.book_new();

  for (const sheet of importTemplateSheets) {
    const rows = [sheet.headers, sheet.sampleRow];
    const worksheet = XLSX.utils.aoa_to_sheet(rows);
    XLSX.utils.book_append_sheet(workbook, worksheet, sheet.sheetName);
  }

  return workbook;
}

export function downloadImportTemplateWorkbook() {
  const workbook = createTemplateWorkbook();
  const output = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
  const blob = new Blob([output], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });

  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = objectUrl;
  anchor.download = "wealthos-import-template.xlsx";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(objectUrl);
}
